apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-kpsh
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/pkhander-tenant/devfile-sample-python-basic-1/devfile-sample-kpsh@sha256:c449315d457673ba838713ed2bf40da776e778150763734675d825e4b8e6040c
        name: my-nodejs
        resources: {}
status: {}
